apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: {{ include "care.namespace" . }}
  labels:
    {{- include "care.n8n.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.n8n.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
